server.port: 8082

spring:
  profiles:
    include: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties.hibernate:
      format_sql: true
  liquibase:
    enabled: true
    drop-first: false
